# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29b477f9dae1820c5114475e531c49ad1c05d8f28f2ddc5ccca1374aa04b0b93651a3e0899e08510740331fd8fbac633176a37ac4d38cd13df41574f7bbc0f41

test:
  secret_key_base: a37b8488afaca34d50564bb47b1d2fcabf53026cebb5fdd906033eef27f31524444b3d85379dbc174d3a850bd976703815b421ad15e2ecc53b34810f1037360d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
